#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Connect to redis
rdb = agent.redis_connect()

if "mail_server" in data and data["mail_server"] != os.getenv("MAIL_SERVER"):
    mail_server = data["mail_server"]
    if not rdb.exists(f"module/{mail_server}/srv/tcp/imap"):
            agent.set_status('validation-failed')
            json.dump([{'field':'mail_server','parameter':'mail_server','value': data["mail_server"],'error':'mail_server_is_not_valid'}], fp=sys.stdout)
            sys.exit(3)
