#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
host = data["host"]
h2hs = data.get("http2https", True)

# Configure Traefik route for API
set_route_data = {
    'instance': os.environ['MODULE_ID'],
    'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
    'host': host,
    'http2https': h2hs,
    'lets_encrypt_check': True,
    'lets_encrypt_cleanup': True,
}
if 'lets_encrypt' in data:
    set_route_data['lets_encrypt'] = data['lets_encrypt']

agent.set_route(set_route_data)
