#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

plugins = 'archive,zipdownload,managesieve,markasjunk,' + data.get("plugins",'')
upload_max_filesize = str(data.get("upload_max_filesize", '5')) + 'M'

# Setup configuration from user input.
agent.set_env("MAIL_SERVER", data["mail_server"])
agent.set_env("ROUNDCUBEMAIL_PLUGINS", plugins)
agent.set_env("ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE", upload_max_filesize)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
