#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
rdb = agent.redis_connect()

# Setup default values
mail_server = data["mail_server"]
mail_server = rdb.hget(f"module/{mail_server}/srv/tcp/imap", "host") or ""

# for now it seems I cannot use no encryption on smtp
with open("config/config.nethserver.php", "w") as f:
    f.write("<?php \n")
    f.write("$config['imap_conn_options'] = ['ssl'=>['verify_peer'=>false,'verify_peer_name'=>false,'allow_self_signed'=>true], ]; \n")
    f.write("$config['smtp_conn_options'] = ['ssl'=>['verify_peer'=>false,'verify_peer_name'=>false,'allow_self_signed'=>true], ]; \n")

with open("config/config.managesieve.php", "w") as f:
    f.write("<?php\n")
    f.write("$config['managesieve_host'] = 'tls://"+mail_server+":4190';\n")
    f.write("$config['managesieve_conn_options'] = ['ssl'=>['verify_peer'=>false,'verify_peer_name'=>false,'allow_self_signed'=>true], ];\n")
