#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Write default settings of roundcubemail
#
with open("config/config.nethserver.php", "w") as f:
    f.write("<?php \n")
    # we need a full email adress with foo@domain.com
    f.write("$config['login_username_filter'] = 'email'; \n")
    # allow the browser to save login/credential and to fill them
    f.write("$config['login_autocomplete'] = 2; \n")
