#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

if str(event['module']) != os.environ['MAIL_SERVER']:
    print(agent.SD_DEBUG + "Event ignored: module is different")
    sys.exit(2)
