#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)
# if the mail server has been removed, we try to discover the new mail server
if event['module'] == os.environ['MAIL_SERVER']:
   agent.run_helper("systemctl", "--user", "try-restart", "roundcubemail.service").check_returncode()
