#!/usr/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# Restart if running, ignore if stopped
systemctl --user try-restart roundcubemail.service
