#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

rdb = agent.redis_connect() # full read-only access on every key

config["mail_server"] = os.getenv("MAIL_SERVER", "") # the value is the Mail module UUID!
config["plugins"] = os.getenv("ROUNDCUBEMAIL_PLUGINS","")
config["upload_max_filesize"] = os.getenv("ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE","10").replace('M','')

modules=[]

# we query about all mail server to use it inside the user interface
for key in agent.list_service_providers(rdb,'imap','tcp'):
    modules.append({
        "name": key['module_id'],
        "label": key['mail_hostname'],
        "value": key['module_uuid'],
    })

# use it inside a dropdown
config['mail_server_URL'] = modules

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
