#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "MAIL_SERVER"
        "ROUNDCUBEMAIL_DEFAULT_HOST",
        "ROUNDCUBEMAIL_SMTP_SERVER",
        "ROUNDCUBEMAIL_PLUGINS",
        "ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE",
        "ROUNDCUBEMAIL_DEFAULT_PORT",
        "ROUNDCUBEMAIL_SMTP_PORT",
        "STARTTLS_SMTP",
        "STARTTLS_IMAP",
        "ENCRYPTED_SMTP",
        "ENCRYPTED_IMAP", 
        "TLS_VERIFY_SMTP", 
        "TLS_VERIFY_IMAP",
    ]:
     agent.set_env(evar, original_environment[evar])

agent.dump_env()
