#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "mail_server": os.environ["MAIL_SERVER"],
    "mail_domain": os.environ["MAIL_DOMAIN"],
    "plugins": os.environ["ROUNDCUBEMAIL_PLUGINS"],
    "upload_max_filesize": os.environ["ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE"],
    "http2https": os.environ["TRAEFIK_HTTP2HTTPS"] == 'True',
    "host": os.environ["TRAEFIK_HOST"],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
