#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import os

event_input = json.load(sys.stdin)

if (event_input['module_uuid'] == os.getenv('MAIL_MODULE_UUID')
    and event_input['reason'] == 'destroy-module'):
    # the mail server has been removed we stop
    sys.exit(2)
