#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

mail_server = event['module_id']
module_uuid = event['module_uuid']

# Talk with agent using file descriptor.
# Setup configuration from user input.
agent.set_env("MAIL_SERVER", mail_server)
agent.set_env("MAIL_MODULE_UUID", module_uuid)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
